/**
 * OpenAPi NerdWarehouse
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param email 
 * @param firstname 
 * @param lastname 
 * @param password 
 */
data class NewUserDto (

    val email: kotlin.String? = null,
    val firstname: kotlin.String? = null,
    val lastname: kotlin.String? = null,
    val password: kotlin.String? = null
) {
}