/**
 * OpenAPi NerdWarehouse
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.unical.amazing.swagger.models

data class OrderDto(
    val id: Long,
    val products: List<ProductWithQuantityDto>
)

data class ProductWithQuantityDto(
    val product: ProductDto,
    val quantity: Int
)