/**
 * OpenAPi NerdWarehouse
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package com.unical.amazing.swagger.models

/**
 *
 * @param totalPrice
 * @param paymentMethod
 * @param userId
 * @param productDtoList
 */
data class OrderDto(
    val id: Int,
    val product: List<ProductDto>,
    val quantity: Int
)
{
}