/**
 * OpenAPi NerdWarehouse
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import com.unical.amazing.model.Order
import com.unical.amazing.model.account.WishlistModel
import com.unical.amazing.swagger.models.AddressDto


data class UserDto (

    val id: String,
    val username: String,
    val firstName: String,
    val lastName: String,
    val email: String,
    val addresses: List<AddressDto>,
    val phone: String = addresses.get(0).phone,
    val CAP: Int= addresses.get(0).cap,
    val city: String= addresses.get(0).city,
    val country: String= addresses.get(0).country,
    val picurl: String? = null,
    val orders: List<Order>? = null,
    val wishlistModels: List<WishlistModel>? = null
)


