/**
 * OpenAPi NerdWarehouse
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models

import com.unical.amazing.model.Order
import com.unical.amazing.model.account.WishlistModel



data class UserDto (

    val id: String,
    val firstName: String,
    val surname: String,
    val email: String,
    val address: String,
    val phone: String,
    val CAP: Int,
    val city: String,
    val country: String,
    val picurl: String,
    val orders: List<Order>,
    val wishlistModels: List<WishlistModel>
)