/**
 * OpenAPi NerdWarehouse
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param email 
 * @param firstName 
 * @param lastName 
 * @param id 
 */
data class UserDto (

    val email: kotlin.String? = null,
    val firstName: kotlin.String? = null,
    val lastName: kotlin.String? = null,
    val id: kotlin.Long? = null
) {
}