/**
 * OpenAPi NerdWarehouse
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.apis

import io.swagger.client.models.ProductDto

import io.swagger.client.infrastructure.*

class ProductApi(basePath: kotlin.String = "http://localhost:8010/") : ApiClient(basePath) {

    /**
     * 
     * 
     * @param body  
     * @return ProductDto
     */
    @Suppress("UNCHECKED_CAST")
    fun addProduct(body: ProductDto): ProductDto {
        val localVariableBody: kotlin.Any? = body
        val localVariableConfig = RequestConfig(
                RequestMethod.POST,
                "/v1/products"
        )
        val response = request<ProductDto>(
                localVariableConfig, localVariableBody
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as ProductDto
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param productId  
     * @return void
     */
    fun deleteProduct(productId: kotlin.Long): Unit {
        val localVariableConfig = RequestConfig(
                RequestMethod.DELETE,
                "/v1/products/{productId}".replace("{" + "productId" + "}", "$productId")
        )
        val response = request<Any?>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> Unit
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param title  
     * @return kotlin.Array<ProductDto>
     */
    @Suppress("UNCHECKED_CAST")
    fun findByTitleLike(title: kotlin.String): kotlin.Array<ProductDto> {
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>().apply {
            put("title", listOf(title.toString()))
        }
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/v1/product/title", query = localVariableQuery
        )
        val response = request<kotlin.Array<ProductDto>>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.Array<ProductDto>
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @return kotlin.Array<ProductDto>
     */
    @Suppress("UNCHECKED_CAST")
    fun getAll(): kotlin.Array<ProductDto> {
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/v1/all-products"
        )
        val response = request<kotlin.Array<ProductDto>>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.Array<ProductDto>
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param userId  
     * @return kotlin.Array<ProductDto>
     */
    @Suppress("UNCHECKED_CAST")
    fun getAllByUserId(userId: kotlin.Long): kotlin.Array<ProductDto> {
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/v1/products/{userId}".replace("{" + "userId" + "}", "$userId")
        )
        val response = request<kotlin.Array<ProductDto>>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as kotlin.Array<ProductDto>
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
    /**
     * 
     * 
     * @param id  
     * @return ProductDto
     */
    @Suppress("UNCHECKED_CAST")
    fun getById(id: kotlin.Long): ProductDto {
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/v1/product/{id}".replace("{" + "id" + "}", "$id")
        )
        val response = request<ProductDto>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as ProductDto
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
}
