/**
 * OpenAPi NerdWarehouse
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.apis

import android.content.Context
import com.unical.amazing.R
import com.unical.amazing.model.settings.ConfigHelper
import com.unical.amazing.model.settings.HOST_URL
import com.unical.amazing.swagger.models.WishlistDto
import com.unical.amazing.swagger.models.WishlistUpdateDTO


import io.swagger.client.infrastructure.*

class WishlistApi(context: Context, // Aggiungi il Context come parametro
               basePath: String = "https://$HOST_URL:8443/"
) : ApiClient(basePath, createSecureClient(context, R.raw.truststore, ConfigHelper.getTruststorePassword(context))) {


    @Suppress("UNCHECKED_CAST")
    fun getAllByUser(token: String): Any {
        val headers = mapOf("Authorization" to "Bearer $token")
        val localVariableConfig = RequestConfig(
            RequestMethod.GET,
            "/wishlists/all",
            headers = headers
        )
        val response = request<List<Map<String, Any?>>>(
            localVariableConfig
        )


        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as Any
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> {
                throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            }
            ResponseType.ServerError -> {
                throw ServerException((response as ServerError<*>).message ?: "Server error")
            }
        }
    }


    @Suppress("UNCHECKED_CAST")
    fun getsharedwithUser(token: String): Any {
        val headers = mapOf("Authorization" to "Bearer $token")
        val localVariableConfig = RequestConfig(
            RequestMethod.GET,
            "/wishlists/shared",
            headers = headers
        )
        val response = request<List<Map<String, Any?>>>(
            localVariableConfig
        )


        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as Any
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> {
                throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            }
            ResponseType.ServerError -> {
                throw ServerException((response as ServerError<*>).message ?: "Server error")
            }
        }
    }


    @Suppress("UNCHECKED_CAST")
    fun getpublic(token: String): Any {
        val headers = mapOf("Authorization" to "Bearer $token")
        val localVariableConfig = RequestConfig(
            RequestMethod.GET,
            "/wishlists/public",
            headers = headers
        )
        val response = request<List<Map<String, Any?>>>(
            localVariableConfig
        )


        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as Any
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> {
                throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            }
            ResponseType.ServerError -> {
                throw ServerException((response as ServerError<*>).message ?: "Server error")
            }
        }
    }

    @Suppress("UNCHECKED_CAST")
    fun create(token: String,wishlist: WishlistDto): Any{
        val headers = mapOf("Authorization" to "Bearer $token")
        val localVariableConfig = RequestConfig(
            RequestMethod.POST,
            "/wishlists/add",
            headers = headers
        )
        val response = request<List<Map<String, Any?>>>(
            localVariableConfig,wishlist
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as Any
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> {
                throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            }
            ResponseType.ServerError -> {
                throw ServerException((response as ServerError<*>).message ?: "Server error")
            }
        }
    }

    @Suppress("UNCHECKED_CAST")
    fun delete(token: String,id: Long): Any{
        val headers = mapOf("Authorization" to "Bearer $token")
        val localVariableConfig = RequestConfig(
            RequestMethod.DELETE,
            "/wishlists/delete/$id",
            headers = headers
        )
        val response = request<List<Map<String, Any?>>>(
            localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as Any
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> {
                throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            }
            ResponseType.ServerError -> {
                throw ServerException((response as ServerError<*>).message ?: "Server error")
            }
        }
    }

    @Suppress("UNCHECKED_CAST")
    fun update(token: String, wishlistUpdateDTO: WishlistUpdateDTO): Any {
        val headers = mapOf("Authorization" to "Bearer $token")
        val localVariableConfig = RequestConfig(
            RequestMethod.PUT,
            "/wishlists/update",
            headers = headers
        )
        println(wishlistUpdateDTO)
        val response = request<List<Map<String, Any?>>>(
            localVariableConfig, wishlistUpdateDTO
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as Any
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> {
                // Log dettagliato dell'errore
                println("ClientError: ${response.responseType}")
                println("Headers: ${response.headers}")
                println("Status Code: ${response.statusCode}")
                throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            }
            ResponseType.ServerError -> {
                throw ServerException((response as ServerError<*>).message ?: "Server error")
            }
        }
    }



    @Suppress("UNCHECKED_CAST")
    fun addProductToWishlist(token: String,productId: Long, wishlistId: Long): Any{
        val headers = mapOf("Authorization" to "Bearer $token")
        val localVariableConfig = RequestConfig(
            RequestMethod.GET,
            "/wishlists/addItem/$wishlistId/$productId",
            headers = headers
        )
        val response = request<List<Map<String, Any?>>>(
            localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as Any
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> {
                throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            }
            ResponseType.ServerError -> {
                throw ServerException((response as ServerError<*>).message ?: "Server error")
            }
        }
    }

    @Suppress("UNCHECKED_CAST")
    fun removeProductFromWishlist(token: String,productId: Long, wishlistId: Long):Any{
        val headers = mapOf("Authorization" to "Bearer $token")
        val localVariableConfig = RequestConfig(
            RequestMethod.DELETE,
            "/wishlists/removeItem/$wishlistId/$productId",
            headers = headers
        )
        val response = request<List<Map<String, Any?>>>(
            localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as Any
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> {
                throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            }
            ResponseType.ServerError -> {
                throw ServerException((response as ServerError<*>).message ?: "Server error")
            }
        }

    }
}
