package com.unical.amazing.view.account

import android.content.Context
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.*
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Delete
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp
import androidx.lifecycle.viewmodel.compose.viewModel
import com.unical.amazing.swagger.models.ProductDto
import com.unical.amazing.swagger.models.UserWDto
import com.unical.amazing.swagger.models.WishlistDto
import com.unical.amazing.viewmodel.account.WishlistViewModel
import com.unical.amazing.viewmodel.factories.WishlistViewModelFactory

@Composable
fun WishlistScreen(context: Context) {
    val viewModelFactory = remember { WishlistViewModelFactory(context) }
    val wishlistViewModel: WishlistViewModel = viewModel(factory = viewModelFactory)
    val wishlists by wishlistViewModel.wishlists.collectAsState()
    val sharedWishlists by wishlistViewModel.sharedwishlists.collectAsState()
    val publicWishlists by wishlistViewModel.publicwishlists.collectAsState()

    var newWishlistName by remember { mutableStateOf("") }

    LazyColumn(
        modifier = Modifier
            .padding(16.dp)
            .fillMaxSize()
    ) {
        item {
            Text("Le mie Wishlist", style = MaterialTheme.typography.h5, modifier = Modifier.padding(bottom = 16.dp))
        }

        // Personal Wishlists Section
        wishlists?.let { wishlists ->
            items(wishlists) { wishlist ->
                WishlistView(wishlist, onDelete = { wishlistViewModel.deletewishlist(it) }, viewModel = wishlistViewModel)
                Divider(color = Color.Gray, thickness = 0.5.dp)
            }
            item {
                Column {
                    TextField(
                        value = newWishlistName,
                        onValueChange = { newWishlistName = it },
                        label = { Text("Nome nuova lista") },
                        modifier = Modifier.fillMaxWidth()
                    )
                    Button(
                        onClick = {
                            if (newWishlistName.isNotEmpty()) {
                                val newWishlist = WishlistDto(
                                    id = 0, // assuming id will be generated by backend
                                    name = newWishlistName,
                                    visibility = "PRIVATE",
                                    items = emptyList()
                                )
                                wishlistViewModel.createwishlist(newWishlist)
                                newWishlistName = "" // Reset the text field
                            }
                        }
                    ) {
                        Text("Crea nuova lista dei desideri")
                    }
                }
                Spacer(modifier = Modifier.height(16.dp)) // Aggiunge uno spazio alla fine
            }
        } ?: item {
            Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(16.dp),
                contentAlignment = Alignment.Center
            ) {
                Text("Caricamento wishlist...")
            }
        }

        item {
            Text("Wishlist Condivise con te da altri utenti", style = MaterialTheme.typography.h5, modifier = Modifier.padding(vertical = 16.dp))
        }

        // Shared Wishlists Section
        sharedWishlists?.let { sharedWishlists ->
            items(sharedWishlists) { wishlist ->
                WishlistView(wishlist, isShared = true, viewModel = wishlistViewModel)
                Divider(color = Color.Gray, thickness = 0.5.dp)
            }
        } ?: item {
            Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(16.dp),
                contentAlignment = Alignment.Center
            ) {
                Text("Caricamento wishlist condivise...")
            }
        }

        item {
            Text("Wishlist Pubbliche", style = MaterialTheme.typography.h5, modifier = Modifier.padding(vertical = 16.dp))
        }

        // Public Wishlists Section
        publicWishlists?.let { publicWishlists ->
            items(publicWishlists) { wishlist ->
                WishlistView(wishlist, isShared = true, viewModel = wishlistViewModel)
                Divider(color = Color.Gray, thickness = 0.5.dp)
            }
        } ?: item {
            Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(16.dp),
                contentAlignment = Alignment.Center
            ) {
                Text("Caricamento wishlist pubbliche...")
            }
        }

        // Spacer to add extra vertical space
        item {
            Spacer(modifier = Modifier.height(200.dp)) // Adjust height as needed
        }
    }
}

@Composable
fun WishlistView(
    wishlistDto: WishlistDto,
    isShared: Boolean = false,
    onDelete: (Long) -> Unit = {},
    viewModel: WishlistViewModel
) {
    var visibility by remember { mutableStateOf(wishlistDto.visibility) }
    var expanded by remember { mutableStateOf(false) }
    var name by remember { mutableStateOf(wishlistDto.name) }
    var modified by remember { mutableStateOf(false) }

    var sharedUsers by remember { mutableStateOf(wishlistDto.sharedwith?.map { it.username } ?: emptyList()) }
    var showDialog by remember { mutableStateOf(false) }

    Card(
        shape = RoundedCornerShape(8.dp),
        backgroundColor = MaterialTheme.colors.surface,
        elevation = 4.dp,
        modifier = Modifier
            .fillMaxWidth()
            .padding(vertical = 8.dp)
    ) {
        Column(modifier = Modifier.padding(16.dp)) {
            TextField(
                value = name,
                onValueChange = {
                    name = it
                    modified = true
                },
                label = { Text("Nome") },
                modifier = Modifier.fillMaxWidth(),
                enabled = !isShared // Disabilita modifica del nome se è condivisa
            )
            wishlistDto.items?.forEach { item ->
                ItemView(
                    item,
                    wishlistDto.id,
                    isShared = isShared,
                    onRemoveProduct = { productId, wishlistId ->
                        viewModel.removeProductFromWishlist(productId, wishlistId) // Chiamata alla funzione di rimozione
                    }
                )
            }
            if (!isShared) {
                Button(onClick = { onDelete(wishlistDto.id) }) {
                    Text("Rimuovi lista dei desideri")
                }
                Row(
                    verticalAlignment = Alignment.CenterVertically
                ) {
                    Text("Visibilità: ", modifier = Modifier.padding(end = 4.dp))
                    Box {
                        Button(onClick = { expanded = true }) {
                            Text(visibility)
                        }
                        DropdownMenu(
                            expanded = expanded,
                            onDismissRequest = { expanded = false }
                        ) {
                            DropdownMenuItem(onClick = {
                                visibility = "PUBLIC"
                                expanded = false
                                modified = true
                            }) {
                                Text("PUBBLICA")
                            }
                            DropdownMenuItem(onClick = {
                                visibility = "PRIVATE"
                                expanded = false
                                modified = true
                            }) {
                                Text("PRIVATA")
                            }
                            DropdownMenuItem(onClick = {
                                visibility = "SHARED"
                                expanded = false
                                modified = true
                            }) {
                                Text("CONDIVISA")
                            }
                        }
                    }
                }
                if (visibility == "SHARED") {
                    Column {
                        sharedUsers.forEach { username ->
                            Row(
                                verticalAlignment = Alignment.CenterVertically,
                                modifier = Modifier.padding(vertical = 4.dp)
                            ) {
                                Text(username, modifier = Modifier.weight(1f))
                                IconButton(onClick = {
                                    sharedUsers = sharedUsers.filter { it != username }
                                    modified = true
                                }) {
                                    Icon(Icons.Default.Delete, contentDescription = "Remove user")
                                }
                            }
                        }
                        Button(onClick = { showDialog = true }) {
                            Text("Aggiungi utente")
                        }
                    }
                }
                if (modified) {
                    Spacer(modifier = Modifier.height(8.dp))
                    Button(onClick = {
                        val updatedWishlist = wishlistDto.copy(
                            name = name,
                            visibility = visibility,
                            sharedwith = if (visibility == "SHARED") sharedUsers.map { UserWDto(username = it) } else null
                        )
                        viewModel.updatewishlist(updatedWishlist, sharedUsers)
                        modified = false
                    }) {
                        Text("Salva modifiche")
                    }
                }
            }
        }
    }

    if (showDialog) {
        AddUserDialog(
            onDismiss = { showDialog = false },
            onAddUser = { username ->
                sharedUsers = sharedUsers.plus(username)
                showDialog = false
                modified = true
            }
        )
    }
}


@Composable
fun AddUserDialog(
    onDismiss: () -> Unit,
    onAddUser: (String) -> Unit
) {
    var username by remember { mutableStateOf("") }

    AlertDialog(
        onDismissRequest = onDismiss,
        title = { Text("Aggiungi utente") },
        text = {
            Column {
                TextField(
                    value = username,
                    onValueChange = { username = it },
                    label = { Text("Username") },
                    modifier = Modifier.fillMaxWidth()
                )
            }
        },
        confirmButton = {
            Button(onClick = {
                onAddUser(username)
            }) {
                Text("Aggiungi")
            }
        },
        dismissButton = {
            Button(onClick = onDismiss) {
                Text("Annulla")
            }
        }
    )
}

@Composable
fun ItemView(
    item: ProductDto,
    wishlistId: Long,
    isShared: Boolean = false,
    onRemoveProduct: (Long, Long) -> Unit // Aggiungi questo parametro
) {
    Card(
        shape = RoundedCornerShape(8.dp),
        backgroundColor = MaterialTheme.colors.surface,
        elevation = 4.dp,
        modifier = Modifier
            .fillMaxWidth()
            .padding(vertical = 8.dp)
    ) {
        Column(modifier = Modifier.padding(16.dp)) {
            item.title?.let { Text(text = it, style = MaterialTheme.typography.body1, color = Color.Black) }
            Text(text = "Prezzo: ${item.price}", style = MaterialTheme.typography.body2, color = Color.Black)
            if (!isShared) {
                Button(onClick = { item.id?.let { onRemoveProduct(it, wishlistId) } }) { // Richiama la funzione di rimozione
                    Text("Rimuovi dall'elenco dei desideri")
                }
            }
        }
    }
}


